# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ReactNative CI/CD

on:
  push:
    branches: [ main,deploy ]
  pull_request:
    branches: [ main,deploy ]

jobs:
  build-android:
    needs: install-and-test
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - name: Build Android Release
            run:  cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
            name: app-release.apk
            path: android/app/build/outputs/apk/release/
  build-ios:
      needs: install-and-test
      runs-on: [self-hosted, macos]
      steps:
       - uses: actions/checkout@v2
       - name: Install npm dependencies
         run:  npm install
       - name: Install pod dependencies
         run: |
            cd ios && pod install
       - name: Build app
         run:  xcodebuild -workspace myapp.xcworkspace -scheme myapp archive -archivePath myapp.xcarchive -allowProvisioningUpdates xcodebuild -exportArchive -archivePath ./myapp.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist  mv myapp.ipa ../myapp.ipa
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: myapp.ipa
        path: ios/build/